-- =============================================================================
-- run_reports
--
-- Per-run narrative reports generated by LLM from run data.
-- run_id is nullable: for project-rollup reports it's NULL and source_run_ids
-- holds the aggregated docking_runs.id list.
-- =============================================================================

create table if not exists run_reports (
    id                  uuid primary key default uuid_generate_v4(),
    user_id             uuid references auth.users(id) on delete cascade not null,
    run_id              uuid,
    run_type            text not null check (run_type in ('dock', 'optimize', 'chat_session', 'project')),
    research_question   text,
    display_title       text,
    sections            jsonb not null,
    model               text not null,
    source_run_ids      jsonb,
    status              text not null default 'complete'
                            check (status in ('complete', 'failed')),
    error               text,
    created_at          timestamptz default now() not null,
    regenerated_at      timestamptz
);

-- Idempotency for non-project runs. NULLs distinct in PG unique indexes,
-- so projects with run_id=NULL can coexist freely.
create unique index if not exists uq_run_reports_run
    on run_reports(run_id, run_type)
    where run_id is not null;

alter table run_reports enable row level security;

create policy "Users can view their own run reports"
    on run_reports for select using (auth.uid() = user_id);
create policy "Users can insert their own run reports"
    on run_reports for insert with check (auth.uid() = user_id);
create policy "Users can update their own run reports"
    on run_reports for update using (auth.uid() = user_id);
create policy "Users can delete their own run reports"
    on run_reports for delete using (auth.uid() = user_id);

create index if not exists idx_run_reports_user_date on run_reports(user_id, created_at desc);
create index if not exists idx_run_reports_run on run_reports(run_id, run_type);
